### ISSUE TITLE
extract_by() in scalar context

### ISSUE THREAD

**Issue by leonerd** [syohex/p5-List-Utils-By#4]
Hi there,

I didn't document what `extract_by` does in scalar context, but it turns out some people have been relying on its current behaviour anyway when doing so. What it does now is that because it's just doing

```
return @ret;
```

then in scalar context you get the count of items that had been extracted. This is useful in cases where you just want to know if any were; e.g.

```
if( scalar extract_by { ... } @array )
```

I'd like to add that to the documentation so users can rely on this, but I note that currently your XS implementation would not behave this way. Currently it would return the first element of the list it would have returned in list context.

Would you like to fix this one, so we can declare this behaviour in the docs?

**Comment by syohex** [comment]
Sorry too late reply. I have fixed this at #5.

**Comment by syohex** [comment]
> Would you like to fix this one, so we can declare this behaviour in the docs?

Yes.
