### ISSUE TITLE
Encode::Locale required (maybe during install only)

### ISSUE THREAD

**Issue by skaurus** [syohex/p5-List-Utils-By#9]
Hi!

I haven't checked this thoroughly but when I try to install your module via `carton`, installation fails because `Encode::Locale` is not found in `@INC`. If I install `Encode::Locale` before your module, errors are gone.
So I suppose that your module requires `Encode::Locale` but don't list it somewhere in dependencies.

Thanks for a module!

**Comment by syohex** [comment]
Could you show me your cpanfile for Carton ?

**Comment by skaurus** [comment]
Yes: http://pastebin.com/0Ev1giBy
All these modules are already installed. If I add `List::UtilsBy:;XS` after the `List::Util` entry, it will cause this error.

**Comment by syohex** [comment]
I think this is other package issue. And I cannot reproduce your issue.
`Encode::Locale` is not installed with following `cpanfile`.

```
# only this line
requires 'List::UtilsBy::XS';
```

```
% ag -l Encode::Locale
local/lib/perl5/HTTP/Response.pm
local/lib/perl5/LWP/UserAgent.pm
```

BTW `Encode::Locale` is used by above modules.

**Comment by skaurus** [comment]
OK, thanks.
